services:
  - type: web
    name: ludo-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: WEBAPP_URL
        value: https://ludo-frontend.onrender.com
